// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejjobmxddoadtrqsofli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqam9ibXhkZG9hZHRycXNvZmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjM2ODAsImV4cCI6MjA2NTczOTY4MH0.Vzujg5ccbF1pTjXt-Ak0gLihlydGW0RH-Pn_cL-bkdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);